// GÉNÉRÉ par art/batiments/propositions/essai-claude/outils/installer-moteurs.cjs (hors git)
// — ne pas éditer à la main : relancer l'installation.
// Les décors de bâtiments-moteur qui ont leurs QUATRE vues (reprise des sprites de Codex,
// repixelisée, 2026-10-09) : « <clé>-fr », « -bl », « -br » à côté de la clé nue. Cf.
// engineOrient.js. Les scènes animées n'y sont pas : leur animation est cuite sur l'ancien
// dessin (granary-cosmic-8, mint-cosmic-8, mint-cosmic-9, mint-prop-forge, mint-prop-forge-grand, mint-prop-house, mint-prop-house-grand, mint-moneta, mint-moneta-grand, ancestralcult-prop, cosmic-ancestral_cult-7, cosmic-ancestral_cult-8, cult-mausoleum, cult-memorial, cult-memorial-grand, cult-vesta, cosmic-observatories-8, cosmic-observatories-9, watch-prop, cosmic-watch-7, cosmic-watch-8, cosmic-watch-9).
export const ENGINE_ORIENTED_KEYS = [
  'bank-basilica-roman', 'bank-basilica-roman-grand', 'bank-cosmic-7', 'bank-cosmic-8',
  'bank-cosmic-9', 'exchange-prop-stall', 'exchange-prop-stall-grand', 'bank-house-neoclassical',
  'bank-house-neoclassical-grand', 'bank-house-renaissance', 'bank-house-renaissance-grand', 'bank-house-glass',
  'bank-house-glass-grand', 'caravan-cosmic-7', 'caravan-cosmic-8', 'caravan-cosmic-9',
  'forager-cosmic-7', 'forager-cosmic-8', 'forager-cosmic-9', 'forager-hortus-classical',
  'forager-hortus-classical-grand', 'forager-greenhouse', 'forager-greenhouse-grand', 'granary-cosmic-7',
  'granary-cosmic-9', 'granary-warehouse', 'granary-warehouse-grand', 'granary-hall',
  'granary-hall-grand', 'granary-horreum-classical', 'granary-horreum-classical-grand', 'granary-hub',
  'granary-hub-grand', 'granary-prop-silo', 'granary-prop-silo-grand', 'guild-chamber',
  'guild-chamber-grand', 'guild-collegium', 'guild-collegium-grand', 'guild-consortium',
  'guild-cosmic-7', 'guild-cosmic-8', 'guild-cosmic-9', 'guild-prop-lodge',
  'guild-prop-lodge-grand', 'guild-house', 'guild-house-grand', 'market-cosmic-7',
  'market-cosmic-8', 'market-cosmic-9', 'market-prop-stall', 'market-prop-stall-grand',
  'market-hall-tent', 'market-hall-glass', 'market-hall-glass-grand', 'market-macellum',
  'market-macellum-grand', 'market-plaza-neon', 'market-plaza-neon-grand', 'mint-cosmic-7',
  'mint-house-digital', 'mint-house-digital-grand', 'mint-house-steam', 'mint-house-steam-grand',
  'port-cosmic-7', 'port-cosmic-8', 'port-cosmic-9', 'port-prop-house',
  'port-house-classical', 'port-house-classical-grand', 'port-house-industrial', 'port-house-industrial-grand',
  'port-house-medieval', 'port-house-medieval-grand', 'port-house-modern', 'port-house-modern-grand',
  'cosmic-academies-7', 'cosmic-academies-8', 'cosmic-academies-9', 'academies-athenaeum',
  'academies-prop-yard', 'academies-prop-yard-grand', 'academies-institute', 'academies-modern',
  'academies-renaissance', 'cosmic-libraries-7', 'cosmic-libraries-8', 'cosmic-libraries-9',
  'libraries-prop-archive', 'libraries-prop-archive-grand', 'libraries-classical', 'libraries-classical-grand',
  'libraries-grand', 'libraries-grand-grand', 'libraries-modern', 'libraries-modern-grand',
  'libraries-monastic', 'libraries-monastic-grand', 'cosmic-think_tanks-7', 'cosmic-think_tanks-8',
  'cosmic-think_tanks-9', 'think-chancellery', 'think-chancellery-grand', 'think-prop-council',
  'think-prop-council-grand', 'think-institute', 'think-institute-grand', 'think-modern',
  'think-modern-grand', 'think-stoa-roman', 'think-stoa-roman-grand', 'cosmic-storytellers-7',
  'cosmic-storytellers-8', 'cosmic-storytellers-9', 'storyteller-hall', 'storyteller-prop-hut',
  'storyteller-media', 'storyteller-odeon', 'storyteller-theater', 'ancestralcult-back-grand',
  'cosmic-ancestral_cult-9', 'cult-mausoleum-grand', 'cult-shrine', 'cult-shrine-grand',
  'cosmic-schools-7', 'cosmic-schools-8', 'cosmic-schools-9', 'schools-campus',
  'schools-campus-grand', 'schools-prop-yard', 'schools-prop-yard-grand', 'schools-schoolhouse',
  'schools-schoolhouse-grand', 'schools-ludus', 'schools-victorian', 'schools-victorian-grand',
  'cosmic-printing_houses-7', 'cosmic-printing_houses-8', 'cosmic-printing_houses-9', 'printing-prop-workshop',
  'printing-prop-workshop-grand', 'printing-media', 'printing-media-grand', 'printing-press-shop',
  'printing-press-shop-grand', 'printing-scriptorium', 'printing-scriptorium-grand', 'printing-factory',
  'printing-factory-grand', 'cosmic-observatories-7', 'observatories-prop-dial', 'observatories-dome',
  'observatories-dome-grand', 'observatories-horologium', 'observatories-horologium-grand', 'observatories-array',
  'observatories-array-grand', 'observatories-tower', 'observatories-tower-grand', 'cosmic-scribes-7',
  'cosmic-scribes-8', 'cosmic-scribes-9', 'scribes-archive', 'scribes-data',
  'scribes-prop-hall', 'scribes-scriptorium', 'scribes-tabularium', 'cosmic-universities-7',
  'cosmic-universities-8', 'cosmic-universities-9', 'universities-classical', 'universities-classical-grand',
  'universities-collegiate', 'universities-gothic', 'universities-gothic-grand', 'universities-prop-hall',
  'universities-prop-hall-grand', 'universities-modern', 'universities-modern-grand', 'cosmic-bureaucracy-7',
  'cosmic-bureaucracy-8', 'cosmic-bureaucracy-9', 'bureau-office', 'bureau-office-grand',
  'bureau-chancery', 'bureau-chancery-grand', 'bureau-hut', 'bureau-hut-grand',
  'bureau-tabularium', 'bureau-tabularium-grand', 'bureau-tower', 'bureau-tower-grand',
  'ruins-institute', 'ruins-institute-grand', 'cosmic-archive_grids-9', 'archive-vault',
  'archive-vault-grand', 'archive-hut', 'archive-hut-grand', 'archive-records',
  'archive-records-grand', 'archive-grid-grand', 'archive-tabularium', 'archive-tabularium-grand',
  'sewers-prop', 'cosmic-sewers-7', 'cosmic-sewers-8', 'cosmic-sewers-9',
  'sewers-classical', 'sewers-medieval', 'sewers-plant', 'sewers-works',
  'watch-classical', 'watch-industrial', 'cosmic-ministries-7', 'cosmic-ministries-8',
  'cosmic-ministries-9', 'ministries-capitol', 'ministries-capitol-grand', 'ministries-council',
  'ministries-curia', 'ministries-curia-grand', 'cosmic-courthouses-9', 'courthouses-basilica',
  'courthouses-basilica-grand', 'courthouses-lodge', 'courthouses-lodge-grand', 'courthouses-neoclassical',
  'courthouses-neoclassical-grand', 'caravan-truck', 'caravan-wagon', 'caravan-pod',
  'caravan-prop-sacks', 'forager-prop-tree', 'forager-hydro-rack', 'forager-prop-basket',
  'cosmic-arch-9', 'camp-hearth', 'granary-crates', 'guild-officina-forge',
  'guild-officina-potter', 'guild-officina-dyer',
];
